### ISSUE TITLE
word/ poetry input die vice - pidv

### ISSUE THREAD

**Issue by mykeweix** [cwatsonc/words#1]
## User/reader perspective
at Start up,  
you are presented with a list of poems. You select a poem. The poem begins to play. 
**On** the screen you see colored words appearing on a dark colored screen. They move slightly on the screen and Flash quite quickly, at first you can't read it because it's going so fast but you find if you look at it you can decipher what it's saying. _It's as if the words are coming into your head a second or so after you actually see them._ The words appear on the screen but they don't appear exactly over each other they are offset sometimes just a **tiny** bit, Up or down right or left (5pixels perhaps) sometimes a lot. (800 pixels or more) A word can appear at the top of the page, in the corner, directly in the center, mostly they'll appear in one general area at a time (centerish). 

For instance, you'll see a word  then after a pause, you'll see a close grouping of words flashing onto the screen quickly,  but you can comprehend them as the meaning trickles into you consciousness. 
The speed that they come onto the screen does change subtly sometimes it plays faster sometimes it slows way up sometimes it will pause on just one word occasionally a picture will show the picture same as the words can pause for a long time or can Flash so quickly you can barely see it. Another part of the poem may play at a nice slow pace.
### It's unnerving and feels like brainwashing.
The beauty is in comprehending the meaning at this subliminal level. The words and the background can be colored but it seems like certain ranges of color are used. Various colors and color combinations that are hard to read seem to be avoided, or NOT.  :-)  
The poem ends and you are returned to the list. 
_You play the poem again:_
As you watch you see that certain parts of the poem can repeat randomly.
It's the same poem but the chunks are in different orders.
### Poets Perspective: 
This could or should obviously be a separate tool for creating and processing poems.
- Should be able to write normal sentences and insert simple Escape codes that control features.
- There could be codes for location on the screen,  for duration, for color, for randomness. etc
- Seems like there could be a separate module or function to handle the intelligence of color selection
- Some settings can be Global like color font type and size.

The raw file is then "ingested". Meaning it is parsed and saved as a binary
file that can be read by The Poetry app.

**Comment by cwatsonc** [comment]
very divisive ;-)

**Comment by mykeweix** [comment]
Thank you.

**Comment by cwatsonc** [comment]
please scrub this enhancement request and break it into smaller pieces.  If it is completed then remove it.

**Comment by mykeweix** [comment]
I thought this is what you wanted. o brief dicription of what i was looking for in the project.

**Comment by cwatsonc** [comment]
It is but that vision should be present in the project level and not at an
issue level...  As issues are resolved we close them.

Really what I was hoping for was a checkpoint of what remained in the
original vision to be realized -- then break those into smaller initiatives.

CW
